events {
    worker_connections 1024;
}

http {
    default_type application/json;

    upstream order_service {
        server order-service:3000;
    }

    upstream inventory_service {
        server inventory-service:8000;
    }

    upstream notify_service {
        server notify-service:3001;
    }

    server {
        listen 80;

        location /orders {
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /inventory {
            proxy_pass http://inventory_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /notify {
            proxy_pass http://notify_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            access_log off;
            return 200 '{"status":"healthy","service":"api-gateway"}';
            add_header Content-Type application/json;
        }
    }
}
